### ISSUE TITLE
Can you help me get that discord thing

### ISSUE THREAD

**Issue by theblobscp** [LetsChill/LetsChill#1]
I wanna discord thing on my bio thing

**Comment by LetsChill** [comment]
You can simply view the source code of my thing :/

**Comment by theblobscp** [comment]
> You can simply view the source code of my thing :/

Yeah but idk what I need to change for it to display mine

**Comment by LetsChill** [comment]
Oh, join this discord server https://discord.gg/mgtR7Zr5
